### PR TITLE
Fix date and time format validation

### PR DESCRIPTION
**Pull request by maldimirov**
Fixes https://github.com/tlivings/enjoi/issues/63

### CODE REVIEW

**Comment by tlivings** [comment]
Awesome, thanks!

**Comment by tlivings** [comment]
The only question is whether this constitutes a breaking change in version.

**Comment by maldimirov** [comment]
I would say so, because it is way more restricting than before.

**Comment by tlivings** [comment]
:+1:

**Comment by maldimirov** [comment]
I see you already released the change on `npm`. We really appreciate that you are so active 👍

**Comment by tlivings** [comment]
Thank you so much much for the contribution!

**Pull request merged**
