### PR TITLE
Feature/make enjoi compatible with joi 16

### PR DESCRIPTION
**Pull request by rmothilal**
Initial changes to update code to work with latest version of Joi and Hapi frameworks.
The code is still a work in progress and will need changes to the allOf extension in the resolver.js file.
Joi v16 and above no longer support string coercion for objects so I added some code from https://gist.github.com/romankaravia/d16928b520dc7e86bab3a3b245e83561 to allow for strings to be converted to array and objects. I am having issues with the remaining tests for custom functions as well. 
Please feel free to let me know what changes are required

### CODE REVIEW

**Comment by tlivings** [comment]
I had to merge a previous PR with less changes that creates conflicts in this PR.

You should be able to pull and rebase them into this PR with minimal impact.

**Comment by rmothilal** [comment]
@tlivings i have updated the branch with the lastest merge to master. Please let me know if you require anything else

**Comment by tlivings** [comment]
Thanks for the updates.

Can you call attention to areas where you were still seeing issues?

**Comment by rmothilal** [comment]
@tlivings im having issues with the resolver.js and the converting the allOf extension into work with the updated joi version. and there are some unit tests which are causing me an issue

**Comment by tlivings** [comment]
Which ones?

**Comment by rmothilal** [comment]
> Which ones?

test-directives.js
test-enjoi.js
test-options.js

not all of them but there are some tests in there that complain that TypeError: this.string(...).foo is not a function and TypeError: this.string(...).baz is not a function

**Comment by tlivings** [comment]
Closing this since #90 landed with these commits.

**Pull request closed without merging**
