### PR TITLE
when undefined minLenght should be default to 0

### PR DESCRIPTION
**Pull request by pibi**
As per http://json-schema.org/latest/json-schema-validation.html#anchor29

### CODE REVIEW

**Comment by pibi** [comment]
@tlivings Hi, any news about that? Should I have to change/add something? 

please let me know,
thanks!

**Comment by tlivings** [comment]
Looks OK to me.

**Comment by pibi** [comment]
gosh, I missed to bump the package version. 
@tlivings should I have to do that? the new version should let swaggerize-routes to use our patched version.

thanks!

**Comment by tlivings** [comment]
Publisher should bump, not PR :)

**Comment by pibi** [comment]
@tlivings :-) so, can you please publish this? thanks a lot!

**Comment by tlivings** [comment]
Already done!

**Pull request merged**
