### PR TITLE
use joi.link to only resolve strictly recursive self-references

### PR DESCRIPTION
**Pull request by nlundquist**
... joi.link fails when attempting to resolve to a cousin or uncle node, which is not a scenario we need to handle since that's scenario is not recursive.

### CODE REVIEW

**Comment by nlundquist** [comment]
hey @tlivings could this bugfix get merged? would you like a test to be added?

**Comment by czlowiek488** [comment]
Is it gonna be merged? I need this in my project.

**Comment by czlowiek488** [comment]
@tlivings Hey, is it something wrong with this PR? Many people is waiting for it.

**Comment by tlivings** [comment]
Sorry this fell off my radar. Reviewing now.

**Comment by tlivings** [comment]
Can you add a test?

thanks.

**Comment by czlowiek488** [comment]
@nlundquist

**Comment by nlundquist** [comment]
just pushed that test, apologies for the delay.

**Review by tlivings — APPROVED** [review]
:+1:

**Pull request merged**
