### PR TITLE
added ability to set defaults in schema

### PR DESCRIPTION
**Pull request by hpadrick**
Allows setting a joi default value from the schema

### CODE REVIEW

**Comment by hpadrick** [comment]
Hi. We would love to be able to set default values from the JSON spec. This was a quick implementation; please let me know what you think. 

Thank you!

**Comment by hpadrick** [comment]
Bump

**Comment by tlivings** [comment]
It looks as though the build is failing.

**Comment by hpadrick** [comment]
Fixed. Let me know about the impl. Thanks.

**Comment by hpadrick** [comment]
Bump

**Pull request merged**
